import '../models/category_model.dart';

final List<CategoryModel> expenseCategories = [
  CategoryModel(name: 'Food', iconKey: 'food', type: 'Expense'),
  CategoryModel(name: 'Transport', iconKey: 'car', type: 'Expense'),
  CategoryModel(name: 'Shopping', iconKey: 'shopping', type: 'Expense'),
  CategoryModel(name: 'Bills', iconKey: 'bills', type: 'Expense'),
  CategoryModel(name: 'Education', iconKey: 'education', type: 'Expense'),
  CategoryModel(name: 'Health', iconKey: 'health', type: 'Expense'),
  CategoryModel(name: 'Groceries', iconKey: 'groceries', type: 'Expense'),
  CategoryModel(name: 'Dining Out', iconKey: 'restaurant', type: 'Expense'),
  CategoryModel(name: 'Utilities', iconKey: 'utilities', type: 'Expense'),
  CategoryModel(name: 'Travel', iconKey: 'travel', type: 'Expense'),
  CategoryModel(name: 'Rent', iconKey: 'rent', type: 'Expense'),
  CategoryModel(name: 'Entertainment', iconKey: 'entertainment', type: 'Expense'),
  CategoryModel(name: 'Insurance', iconKey: 'insurance', type: 'Expense'),
  CategoryModel(name: 'Pet Care', iconKey: 'pet', type: 'Expense'),
  CategoryModel(name: 'Kids/Family', iconKey: 'family', type: 'Expense'),
  CategoryModel(name: 'Subscriptions', iconKey: 'subscriptions', type: 'Expense'),
  CategoryModel(name: 'Debt Payments', iconKey: 'debt', type: 'Expense'),
  CategoryModel(name: 'Gifts Given', iconKey: 'gifts', type: 'Expense'),
  CategoryModel(name: 'Repairs', iconKey: 'repairs', type: 'Expense'),
  CategoryModel(name: 'Clothing', iconKey: 'clothing', type: 'Expense'),
  CategoryModel(name: 'Beauty', iconKey: 'beauty', type: 'Expense'),
  CategoryModel(name: 'Hobbies', iconKey: 'hobbies', type: 'Expense'),
  CategoryModel(name: 'Sport', iconKey: 'sport', type: 'Expense'),
  CategoryModel(name: 'Commute', iconKey: 'commute', type: 'Expense'),
  CategoryModel(name: 'Parking', iconKey: 'parking', type: 'Expense'),
  CategoryModel(name: 'Car Maintenance', iconKey: 'car_maintenance', type: 'Expense'),
  CategoryModel(name: 'Taxes', iconKey: 'taxes', type: 'Expense'),
  CategoryModel(name: 'Charity', iconKey: 'charity', type: 'Expense'),
  CategoryModel(name: 'Electronics', iconKey: 'electronics', type: 'Expense'),
  CategoryModel(name: 'Furnishings', iconKey: 'furnishings', type: 'Expense'),
  CategoryModel(name: 'Business Expenses', iconKey: 'business', type: 'Expense'),
  CategoryModel(name: 'Legal Fees', iconKey: 'legal', type: 'Expense'),
  CategoryModel(name: 'Bank Fees', iconKey: 'bank', type: 'Expense'),
];

final List<CategoryModel> incomeCategories = [
  CategoryModel(name: 'Salary', iconKey: 'salary', type: 'Income'),
  CategoryModel(name: 'Bonus', iconKey: 'bonus', type: 'Income'),
  CategoryModel(name: 'Investments', iconKey: 'investment', type: 'Income'),
];
