import '../models/category_model.dart';

final List<CategoryModel> expenseCategories = [
  CategoryModel(name: 'Food', iconKey: 'food', type: 'Expense'),
  CategoryModel(name: 'Groceries', iconKey: 'groceries', type: 'Expense'),
  CategoryModel(name: 'Transport', iconKey: 'car', type: 'Expense'),
  CategoryModel(name: 'Shopping', iconKey: 'shopping', type: 'Expense'),
  CategoryModel(name: 'Bills', iconKey: 'bills', type: 'Expense'),
  CategoryModel(name: 'Utilities', iconKey: 'utilities', type: 'Expense'),
  CategoryModel(name: 'Health', iconKey: 'health', type: 'Expense'),
  CategoryModel(name: 'Rent', iconKey: 'rent', type: 'Expense'),
  CategoryModel(name: 'Entertainment', iconKey: 'entertainment', type: 'Expense'),
  CategoryModel(name: 'Education', iconKey: 'education', type: 'Expense'),
  CategoryModel(name: 'Travel', iconKey: 'travel', type: 'Expense'),
  CategoryModel(name: 'Dining Out', iconKey: 'restaurant', type: 'Expense'),
  CategoryModel(name: 'Family & Kids', iconKey: 'family', type: 'Expense'),
  CategoryModel(name: 'Insurance', iconKey: 'insurance', type: 'Expense'),
  CategoryModel(name: 'Clothing', iconKey: 'clothing', type: 'Expense'),
  CategoryModel(name: 'Subscriptions', iconKey: 'subscriptions', type: 'Expense'),
  CategoryModel(name: 'Gifts', iconKey: 'gifts', type: 'Expense'),
  CategoryModel(name: 'Charity', iconKey: 'charity', type: 'Expense'),
  CategoryModel(name: 'Repairs', iconKey: 'repairs', type: 'Expense'),
  CategoryModel(name: 'Beauty', iconKey: 'beauty', type: 'Expense'),
  CategoryModel(name: 'Pet Care', iconKey: 'pet', type: 'Expense'),
  CategoryModel(name: 'Sport', iconKey: 'sport', type: 'Expense'),
  CategoryModel(name: 'Parking', iconKey: 'parking', type: 'Expense'),
  CategoryModel(name: 'Furnishings', iconKey: 'furnishings', type: 'Expense'),
  CategoryModel(name: 'Phone', iconKey: 'phone', type: 'Expense'),
  CategoryModel(name: 'Internet', iconKey: 'internet', type: 'Expense'),
  CategoryModel(name: 'Electronics', iconKey: 'electronics', type: 'Expense'),
  CategoryModel(name: 'Taxes', iconKey: 'taxes', type: 'Expense'),
  CategoryModel(name: 'Subscriptions', iconKey: 'subscriptions', type: 'Expense'),
];

final List<CategoryModel> incomeCategories = [
  CategoryModel(name: 'Salary', iconKey: 'salary', type: 'Income'),
  CategoryModel(name: 'Business', iconKey: 'business', type: 'Income'),
  CategoryModel(name: 'Investments', iconKey: 'investment', type: 'Income'),
  CategoryModel(name: 'Bonus', iconKey: 'bonus', type: 'Income'),
  CategoryModel(name: 'Gift', iconKey: 'gift', type: 'Income'),
  CategoryModel(name: 'Interest', iconKey: 'interest', type: 'Income'),
  CategoryModel(name: 'Refunds', iconKey: 'refund', type: 'Income'),
  CategoryModel(name: 'Rental Income', iconKey: 'rent', type: 'Income'),
  CategoryModel(name: 'Side Income', iconKey: 'side_income', type: 'Income'),
  CategoryModel(name: 'Freelance', iconKey: 'freelance', type: 'Income'),
];
