class Currency {
  final String code;
  final String symbol;
  final String name;

  const Currency(
      {required this.code, required this.symbol, required this.name});
}

final List<Currency> currencies = const [
  Currency(code: 'AED', symbol: 'د.إ', name: 'United Arab Emirates Dirham'),
  Currency(code: 'AFN', symbol: '؋', name: 'Afghan Afghani'),
  Currency(code: 'ALL', symbol: 'L', name: 'Albanian Lek'),
  Currency(code: 'AMD', symbol: '֏', name: 'Armenian Dram'),
  Currency(code: 'ANG', symbol: 'ƒ', name: 'Netherlands Antillean Guilder'),
  Currency(code: 'AOA', symbol: 'Kz', name: 'Angolan Kwanza'),
  Currency(code: 'ARS', symbol: '\$', name: 'Argentine Peso'),
  Currency(code: 'AUD', symbol: '\$', name: 'Australian Dollar'),
  Currency(code: 'AWG', symbol: 'ƒ', name: 'Aruban Florin'),
  Currency(code: 'AZN', symbol: '₼', name: 'Azerbaijani Manat'),
  Currency(
      code: 'BAM', symbol: 'KM', name: 'Bosnia-Herzegovina Convertible Mark'),
  Currency(code: 'BBD', symbol: '\$', name: 'Barbadian Dollar'),
  Currency(code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka'),
  Currency(code: 'BGN', symbol: 'лв', name: 'Bulgarian Lev'),
  Currency(code: 'BHD', symbol: '.د.ب', name: 'Bahraini Dinar'),
  Currency(code: 'BIF', symbol: 'FBu', name: 'Burundian Franc'),
  Currency(code: 'BMD', symbol: '\$', name: 'Bermudian Dollar'),
  Currency(code: 'BND', symbol: '\$', name: 'Brunei Dollar'),
  Currency(code: 'BOB', symbol: 'Bs.', name: 'Bolivian Boliviano'),
  Currency(code: 'BRL', symbol: 'R\$', name: 'Brazilian Real'),
  Currency(code: 'BSD', symbol: '\$', name: 'Bahamian Dollar'),
  Currency(code: 'BTN', symbol: 'Nu.', name: 'Bhutanese Ngultrum'),
  Currency(code: 'BWP', symbol: 'P', name: 'Botswana Pula'),
  Currency(code: 'BYN', symbol: 'Br', name: 'Belarusian Ruble'),
  Currency(code: 'BZD', symbol: 'BZ\$', name: 'Belize Dollar'),
  Currency(code: 'CAD', symbol: '\$', name: 'Canadian Dollar'),
  Currency(code: 'CDF', symbol: 'FC', name: 'Congolese Franc'),
  Currency(code: 'CHF', symbol: 'Fr', name: 'Swiss Franc'),
  Currency(code: 'CLP', symbol: '\$', name: 'Chilean Peso'),
  Currency(code: 'CNY', symbol: '¥', name: 'Chinese Yuan'),
  Currency(code: 'COP', symbol: '\$', name: 'Colombian Peso'),
  Currency(code: 'CRC', symbol: '₡', name: 'Costa Rican Colon'),
  Currency(code: 'CUP', symbol: '\$', name: 'Cuban Peso'),
  Currency(code: 'CZK', symbol: 'Kč', name: 'Czech Koruna'),
  Currency(code: 'DJF', symbol: 'Fdj', name: 'Djiboutian Franc'),
  Currency(code: 'DKK', symbol: 'kr', name: 'Danish Krone'),
  Currency(code: 'DOP', symbol: 'RD\$', name: 'Dominican Peso'),
  Currency(code: 'DZD', symbol: 'دج', name: 'Algerian Dinar'),
  Currency(code: 'EGP', symbol: 'E£', name: 'Egyptian Pound'),
  Currency(code: 'ERN', symbol: 'Nfa', name: 'Eritrean Nakfa'),
  Currency(code: 'ETB', symbol: 'Br', name: 'Ethiopian Birr'),
  Currency(code: 'EUR', symbol: '€', name: 'Euro'),
  Currency(code: 'FJD', symbol: '\$', name: 'Fijian Dollar'),
  Currency(code: 'FKP', symbol: '£', name: 'Falkland Islands Pound'),
  Currency(code: 'GBP', symbol: '£', name: 'British Pound'),
  Currency(code: 'GEL', symbol: 'ლ', name: 'Georgian Lari'),
  Currency(code: 'GHS', symbol: '₵', name: 'Ghanaian Cedi'),
  Currency(code: 'GIP', symbol: '£', name: 'Gibraltar Pound'),
  Currency(code: 'GMD', symbol: 'D', name: 'Gambian Dalasi'),
  Currency(code: 'GNF', symbol: 'FG', name: 'Guinean Franc'),
  Currency(code: 'GTQ', symbol: 'Q', name: 'Guatemalan Quetzal'),
  Currency(code: 'GYD', symbol: '\$', name: 'Guyana Dollar'),
  Currency(code: 'HKD', symbol: '\$', name: 'Hong Kong Dollar'),
  Currency(code: 'HNL', symbol: 'L', name: 'Honduran Lempira'),
  Currency(code: 'HRK', symbol: 'kn', name: 'Croatian Kuna'),
  Currency(code: 'HTG', symbol: 'G', name: 'Haitian Gourde'),
  Currency(code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint'),
  Currency(code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah'),
  Currency(code: 'ILS', symbol: '₪', name: 'Israeli New Shekel'),
  Currency(code: 'INR', symbol: '₹', name: 'Indian Rupee'),
  Currency(code: 'IQD', symbol: 'ع.د', name: 'Iraqi Dinar'),
  Currency(code: 'IRR', symbol: '﷼', name: 'Iranian Rial'),
  Currency(code: 'ISK', symbol: 'kr', name: 'Icelandic Krona'),
  Currency(code: 'JMD', symbol: 'J\$', name: 'Jamaican Dollar'),
  Currency(code: 'JOD', symbol: 'JD', name: 'Jordanian Dinar'),
  Currency(code: 'JPY', symbol: '¥', name: 'Japanese Yen'),
  Currency(code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling'),
  Currency(code: 'ZAR', symbol: 'R', name: 'South African Rand'),
  Currency(code: 'ZMW', symbol: 'ZK', name: 'Zambian Kwacha'),
];
